version: "3.7"

services:
  database:
    image: postgres
    container_name: bbq-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker123
      - POSTGRES_DB=barbecue
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: bbq-api
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    network_mode: host
volumes:
  pgdata:
    driver: local
